In [1]:
import pandas as pd

In [33]:
df_e = pd.read_csv('country_data_e.csv', sep=';', na_values=[""])
df_i = pd.read_csv('country_data_i.csv', sep=';', na_values=[""])
df_m = pd.read_csv('country_data_m.csv', sep=';', na_values=[""])

In [36]:
df_m

,Unnamed: 0,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.936264e+10,2.019176e+10,1.0
1,Albania,NaN,NaN,NaN,NaN,NaN,3.480355e+09,3.922099e+09,4.348070e+09,5.611492e+09,...,1.204421e+10,1.192695e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322825e+10,1.138693e+10,1.186135e+10,1.302506e+10,1.0
2,Angola,5.538749e+09,7.526447e+09,7.648377e+09,6.506230e+09,6.152923e+09,9.129595e+09,8.936064e+09,1.528559e+10,1.781271e+10,...,7.030716e+10,8.379950e+10,1.117897e+11,1.280529e+11,1.367099e+11,1.457122e+11,1.161936e+11,1.011239e+11,1.221238e+11,1.0
3,Antigua and Barbuda,5.772807e+08,6.337306e+08,6.806171e+08,7.278606e+08,7.661989e+08,8.301588e+08,8.007403e+08,8.146153e+08,8.556431e+08,...,1.224253e+09,1.152469e+09,1.142043e+09,1.211412e+09,1.192920e+09,1.275577e+09,1.359195e+09,1.464630e+09,1.510085e+09,1.0
4,Argentina,2.580318e+11,2.721498e+11,2.928590e+11,2.989482e+11,2.835230e+11,2.842038e+11,2.686968e+11,9.772400e+10,1.275870e+11,...,3.329765e+11,4.236274e+11,5.301633e+11,5.459824e+11,5.520251e+11,5.263197e+11,5.947493e+11,5.575314e+11,6.426959e+11,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,Venezuela,7.740773e+10,7.054321e+10,8.584353e+10,9.133120e+10,9.797689e+10,1.171407e+11,1.229040e+11,9.289359e+10,8.362063e+10,...,3.297876e+11,3.931924e+11,3.164822e+11,3.812862e+11,3.710054e+11,4.823593e+11,3.235950e+11,2.792490e+11,1.438410e+11,1.0
158,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.060147e+11,1.159317e+11,1.355394e+11,1.558200e+11,1.712220e+11,1.862047e+11,1.932411e+11,2.052762e+11,2.237799e+11,1.0
159,Zambia,3.807067e+09,3.597221e+09,4.303282e+09,3.537683e+09,3.404312e+09,3.600683e+09,4.094481e+09,4.193846e+09,4.901840e+09,...,1.532834e+10,2.026556e+10,2.346010e+10,2.550337e+10,2.804546e+10,2.715063e+10,2.115439e+10,2.095475e+10,2.586814e+10,1.0
160,Zimbabwe,7.111271e+09,8.553147e+09,8.529572e+09,6.401968e+09,6.858013e+09,6.689958e+09,6.777385e+09,6.342116e+09,5.727592e+09,...,9.665793e+09,1.204166e+10,1.410192e+10,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,2.281301e+10,1.0
161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df_i.rename(columns={'Unnamed: 0': 'Coutnry'}).set_index('Coutnry')['2000'].dropna()

Coutnry
Albania                0.1165
Angola                 0.0684
Antigua and Barbuda    0.1539
Argentina              0.1052
Australia              0.0583
                        ...
United States          0.0210
Uruguay                0.0616
Venezuela              0.1337
Zambia                 0.1281
Zimbabwe               0.1157
Name: 2000, Length: 120, dtype: float64

In [40]:
def clean_and_get_year(df,year):
    clean_df = df.rename(columns={'Unnamed: 0': 'Coutnry'}).set_index('Coutnry')
    year = str(year)
    return clean_df[year].dropna()

In [41]:
clean_and_get_year(df_i, 2017)

Coutnry
Afghanistan            0.0702
Albania                0.0085
Angola                 0.0938
Antigua and Barbuda    0.1272
Argentina              0.0793
                        ...
Vanuatu                0.0834
Venezuela              0.1099
Vietnam                0.0269
Zambia                 0.0622
Zimbabwe               0.0499
Name: 2017, Length: 132, dtype: float64

In [51]:
series_m = clean_and_get_year(df_m, 2015).rename('M')
series_i = clean_and_get_year(df_i, 2015).rename('i')
series_e = clean_and_get_year(df_e, 2015).rename('e')

In [53]:
df_2015= pd.concat([series_m, series_i, series_e], axis=1)

/home/rick/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [66]:
DF = df_2015.dropna()

In [84]:
capital_dict = {
    "Afghanistan": Kabul,
    "Albania": Tirana,
    "Angola": Luanda,
    "Antigua and Barbuda": StJohns,
    "Argentina": BuenosAires,
    "Armenia": Yerevan,
    "Australia": Canberra,
    "Bahrain": Manama,
    "Bangladesh": Dhaka,
    "Barbados": Bridgetown,
    "Belize": Belmopan,
    "Benin": PortoNovo,
    "Bolivia": LaPaz,
    "Botswana": Gaborone,
    "Brazil": Brasilia,
    "Brunei Darussalam": BandarSeriBegawan,
    "Bulgaria":Sofia,
    "Burkina Faso": Ouagadougou,
    "Burundi": Bujumbura,
    "Cambodia": PhnomPenh,
    "Cameroon": Yaounde,
    "Canada": Ottawa,
    "Cape Verde": Praia,
    "Central African Republic": Bangui,
    "Chad": NDjamena,
    "Chile": Santiago,
    "China": Beijing,
    "Colombia": Bogota,
    "Congo": Brazzaville,
    "Costa Rica": SanJose,
    "Croatia": Zagreb,
    "Cuba": Havana,
    "Cyprus": Nicosia,
    "Czechia": Prague,
    "Djibouti": Djibouti,
    "Dominica": Roseau,
    "Dominican Republic": SantoDomingo,
    "DR Congo": Kinshasa,
    "Ecuador": Quito,
    "Egypt": Cairo,
    "El Salvador": SanSalvador,
    "Estonia": Tallinn,
    "Eswatini": Mbabane,
    "EU15":Brussels,
    "EU25":Brussels,
    "EU27":Brussels,
    "EU28":Brussels,
    "Gabon":Libreville,
    "Gambia":Banjul,
    "Georgia":Tbilisi,
    "Ghana":Accra,
    "Grenada":StGeorges,
    "Guatemala":GuatemalaCity,
    "Guinea-Bissau":Bissau,
    "Guyana":Georgetown,
    "Haiti":PortauPrince,
    "Honduras":Tegucigalpa,
    "Hungary":Budapest,
    "Iceland":Reykjavik,
    "India":NewDelhi,
    "Indonesia":Jakarta,
    "Israel":TelAviv,
    "Cote d Ivoire":Yamoussoukro,
    "Jamaica":Kingston,
    "Japan":Tokio,
    "Jordan":Amman,
    "Kazakhstan":Astana,
    "Kenya":Nairobi,
    "Korea":Seoul,
    "Kuwait":KuwaitCity,
    "Kyrgyzstan":Bishkek,
    "Laos":Vientiane,
    "Latvia":Riga,
    "Lesotho":Maseru,
    "Liberia":Monrovia,
    "Lithuania":Vilnius,
    "North Macedonia":Skopje,
    "Madagascar":Antananarivo,
    "Malawi":Lilongwe,
    "Malaysia":KualaLumpur,
    "Maldives":Male,
    "Mali":Bamako,
    "Malta":Valletta,
    "Mauritania":Nouakchott,
    "Mauritius":PortLouis,
    "Mexico":MexicoCity,
    "Moldova":Chisinau,
    "Mongolia":Ulaanbaatar,
    "Montenegro":Podgorica,
    "Morocco":Rabat,
    "Mozambique":Maputo,
    "Myanmar":Naypyidaw,
    "Namibia":Windhoek,
    "Nepal":Kathmandu,
    "New Zealand":Wellington,
    "Nicaragua":Managua,
    "Niger":Niamey,
    "Nigeria":Abuja,
    "Norway":Oslo,
    "Oman":Muscat,
    "Pakistan":Islamabad,
    "Panama":PanamaCity,
    "Papua New Guinea":PortMoresby, 
    "Paraguay":Asuncion,
    "Peru":Lima,
    "Philippines":Manila,
    "Poland":Warsaw,
    "Qatar":Doha,
    "Romania":Bucharest,
    "Russia":Moscow,
    "Rwanda":Kigali,
    "Samoa":Apia,
    "Saudi Arabia":Riyadh,
    "Senegal":Dakar,
    "Seychelles":Victoria,
    "Sierra Leone":Freetown,
    "Singapore":Singapore,
    "Slovakia":Bratislava,
    "Slovenia":Ljubljana,
    "Solomon Islands":Honiara,
    "South Africa":CapeTown,
    "Sri Lanka":SriJayawardenepuraKotte,
    "St Kitts and Nevis":Basseterre,
    "St Lucia":Castries,
    "St Vincent and the Grenadines":Kingstown,
    "Suriname": Paramaribo,
    "Switzerland":Bern,
    "Taiwan":Taipei,
    "Tajikistan":Dushanbe,
    "Tanzania":DaresSalaam,
    "Thailand":Bangkok,
    "Togo":Lome,
    "Tonga":Nukualofa,
    "Tunisia":Tunis,    
    "Turkey":Ankara,
    "Uganda":Kampala,
    "Ukraine":Kiev,
    "United Arab Emirates":AbuDhabi,
    "United States":Washington,
    "Uruguay":Montevideo,
    "Vanuatu":PortVila,
    "Venezuela":Caracas,
    "Vietnam":Hanoi,
    "Zambia":Lusaka,
    "Zimbabwe":Harare,
}

NameError: name 'Kabul' is not defined

In [ ]:
def get_WTO_countries(year):
    """
    construct a list of countries from the WTO data for a particular year
    
    parameters:
        - year: int
    
    side effects:
        - gets data from csv-files, `captial_dict` and `area_dict`
    
    returns:
        - list of countries
        
    """
    df_e = pd.read_csv('country_data_e.csv', sep=';', na_values=[""])
    df_i = pd.read_csv('country_data_i.csv', sep=';', na_values=[""])
    df_m = pd.read_csv('country_data_m.csv', sep=';', na_values=[""])
    
    series_m = clean_and_get_year(df_m, year).rename('M')
    series_i = clean_and_get_year(df_i, year).rename('i')
    series_e = clean_and_get_year(df_e, year).rename('e')
    df = pd.concat([series_m, series_i, series_e], axis=1)
    
    incomplete_data_df = df[pd.isnull(df).any(axis=1)]
    if len(incomplete_data_df) > 0:
        print('WARNING: for the following countries, the data was incomplete:')
        print(incomplete_data_df)
        
    df = df.dropna()
    
    countries = []
    for name in df.index:
        country = Country(
            name, 
            df['M'].at[name], 
            captial_dict[name], 
            df['e'].at[name], 
            df['i'].at[name], 
            1
        )
        countries.append(country)
        
    return countries

In [72]:
countries = []
for name in DF.index:
    country = Country(name, DF['M'].at[name], location, DF['e'].at[name], DF['i'].at[name], sqrt_area)
    countries.append(country)

Albania
Angola
Antigua and Barbuda
Argentina
Armenia
Australia
Bahrain
Bangladesh
Barbados
Belize
Benin
Bolivia
Botswana
Brazil
Brunei Darussalam
Burkina Faso
Burundi
Cambodia
Cameroon
Canada
Cape Verde
Central African Republic
Chad
Chile
China
Colombia
Congo
Costa Rica
Cote d Ivoire
Cuba
DR Congo
Djibouti
Dominica
Dominican Republic
EU28
Ecuador
Egypt
El Salvador
Eswatini
Gabon
Gambia
Georgia
Ghana
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Honduras
Iceland
India
Indonesia
Israel
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Korea
Kuwait
Kyrgyzstan
Laos
Lesotho
Madagascar
Malawi
Malaysia
Maldives
Mali
Mauritania
Mauritius
Mexico
Moldova
Mongolia
Montenegro
Morocco
Mozambique
Myanmar
Namibia
Nepal
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Norway
Oman
Pakistan
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Qatar
Russia
Rwanda
Samoa
Saudi Arabia
Senegal
Seychelles
Sierra Leone
Singapore
Solomon Islands
South Africa
Sri Lanka
St Kitts and Nevis
St Lucia
St Vincent and the Grenadines
Suriname
Switzerland
Taiwan
Tajikistan
Tanzania
Thailand
Togo
Tonga
Tunisia
Turkey
Uganda
Ukraine
United Arab Emirates
United States
Uruguay
Vanuatu
Venezuela
Vietnam
Zambia
Zimbabwe

In [82]:
DF['M'].at['Albania']

11386931489.8

In [73]:
class Country:
    """
    stores country hypterparamters, but also state from the simulation
    """
    
    def __init__(self, name, m, location, e, i, sqrt_area): 
        
        # Variables that stay the same during simulations
        self.name = name
        self.m = m
        self.e = e
        self.i = i
        self.location = location
        self.sqrt_area = sqrt_area
        self.self_reward = None
        
        # State variables, not yet initialized since that will be done in the tournament
        self.fitness = None 
        self.fitness_history = []
    
        # private attributes, they should only be changed with `change_strategy`
        self._strategy = None 
        self._evolution = [] 
        
      
    def __str__(self):
        return f'<{self.name}>'
        
    def __repr__(self):
        return f'<{self.name}>'